spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

api:
  security:
    token:
      secret: ${JWT_SECRET:d367ec6ce788f25f51e3749cdd3925cfae17a67d28ccafcfd8f08eb9b3c21be4}

springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html